services:
  product_manager:
    build:
      context: .
    container_name: product_manager
    command: python ./product_manager/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./product_manager:/app/product_manager
      - ./product_manager/db.sqlite3:/app/product_manager/db.sqlite3
    depends_on:
      - order_manager

  order_manager:
    build:
      context: .
    container_name: order_manager
    command: python ./order_manager/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - ./order_manager:/app/order_manager
      - ./order_manager/db.sqlite3:/app/order_manager/db.sqlite3
